neybor:
  github_url: 'http://github.com/apinstein/neybor'
  tracker_api_token: a00fbc0b53e13a8ad1c8f01b19b0537b
  tracker_project_id: 13545
  ref: refs/heads/master
tourbuzz:
  github_url: 'http://github.com/apinstein/tourbuzz'
  tracker_api_token: a00fbc0b53e13a8ad1c8f01b19b0537b
  tracker_project_id: 15381
  ref: refs/heads/master
tourbuzzplayer:
  github_url: 'http://github.com/lorennorman/tourbuzz-panoviewer'
  tracker_api_token: a00fbc0b53e13a8ad1c8f01b19b0537b
  tracker_project_id: 15381
  ref: refs/heads/master
